# Generated by Django 4.2.7 on 2023-12-23 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0002_personalspendingcategories_delete_personalspending'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalspendingcategories',
            name='spendingDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='personalspendingcategories',
            name='spendingNote',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
