# Generated by Django 4.2.7 on 2023-12-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0005_categories_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalspending',
            name='spendingAmount',
            field=models.FloatField(default=0),
        ),
    ]
